version: '3.4'

services:
  oracle-client:
    image: ${DOCKER_REGISTRY}oracleclient
    build:
      context: .
      dockerfile: Dockerfile
    depends_on: 
      - oracledb

  oracledb:
    # custom image created from https://github.com/christianacca/docker-oracle-xe/tree/no-volume
    image: christianacca/oracle-xe:hr-demodb