version: '3.4'

services:
  oracle-client:
    image: ${DOCKER_REGISTRY}oracleclient
    build:
      context: .
      dockerfile: Dockerfile
    depends_on: 
      - oracledb

  oracledb:
    # https://hub.docker.com/r/christianacca/oracle-xe/
    image: christianacca/oracle-xe:18c